### ISSUE TITLE
[BUG-python/deployment] Duplicate labels in helm chart

### ISSUE THREAD

**Issue by CreMindES** [argilla-io/argilla#5788]
### Describe the bug

[The helm chart in examples](https://github.com/argilla-io/argilla/tree/develop/examples/deployments/k8s/argilla-chart) has duplicate labels `app.kubernetes.io/component: worker` which breaks `kustomize` when wrapping the chart.

### Stacktrace and code to create the bug

`helm template .`

```yaml
...
# Source: argilla/templates/worker-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-argilla-worker
  labels:
    helm.sh/chart: argilla-0.1.0
    app.kubernetes.io/component: worker
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      app.kubernetes.io/name: release-name-worker
      app.kubernetes.io/instance: release-name-worker
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/component: worker
        app.kubernetes.io/name: release-name-worker
        app.kubernetes.io/instance: release-name-worker
        app.kubernetes.io/component: worker
    spec:
...
```

### Expected behavior

`helm template .`

```yaml
# Source: argilla/templates/worker-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-argilla-worker
  labels:
    helm.sh/chart: argilla-0.1.0
    app.kubernetes.io/component: worker
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      app.kubernetes.io/name: release-name-worker
      app.kubernetes.io/instance: release-name-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/component: worker
        app.kubernetes.io/name: release-name-worker
        app.kubernetes.io/instance: release-name-worker
    spec:
```

### Environment

- Argilla Helm Chart 0.1.0
- Helm v3.16.4
- Kustomize 5.4.3
