### ISSUE TITLE
[BUG-python/deployment] deploying on DNS with prefix

### ISSUE THREAD

**Issue by aleksvercau** [argilla-io/argilla#5792]
### Describe the bug

I am using the k8s deployment to deploy Argilla. I updated the `examples/deployments/k8s/argilla-chart/values.yaml` file to use our DNS and use https. The idea is to have it run on our DNS with a specific prefix, like all our other services deployed in kubernetes. However, adding a prefix breaks the application.

### Stacktrace and code to create the bug

This is what is specified in my values file for the ingress:
```
argilla:
  ingress:
    enabled: true
    className: "nginx"
    host: mydns
    tlsSecret: tls-secret
    prefix: /argilla(/|$)(.*)
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
```
And this is how I updated the ingress:

```
{{- if .Values.argilla.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "argilla.fullname" . }}
  labels:
    {{- include "argilla.labels" . | nindent 4 }}
  {{- with .Values.argilla.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.argilla.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.argilla.ingress.host | quote }}
      secretName: {{ .Values.argilla.ingress.tlsSecret }}
  rules:
    - host: {{ .Values.argilla.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.argilla.ingress.prefix | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "argilla.fullname" . }}
                port:
                  number: 6900
{{- end }}
```

When I tried deploying on the plain DNS, without the prefix, it all works fine, when navigating to the url I land on the login page, as expected. When I add the prefix however, the p[age cannot be loaded. In the console I see the following issues:
```
Verify stylesheet URLs: This page failed to load a stylesheet from a URL.
AFFECTED RESOURCES
2 sources
        <link rel="preload" href="/_nuxt/df7f18a.js" as="script">
        <link rel="preload" href="/_nuxt/22e8fc5.js" as="script">
```
And the following errors for multiple files:
```
GET https://mydns/_nuxt/3045c38.js net::ERR_ABORTED 404 (Not Found)
```
when I manually add the prefix to those urls (ex. https://mydns/argilla/_nuxt/3045c38.js net) that cannot be found, the .js is loaded, so it looks like the _nuxt resources are not redirected properly when using a prefix.
I tried adding the BASE_URL environment variable, but that didn't fix it.

```
            - name: BASE_URL
              value: {{ .Values.argilla.ingress.prefix  }}
```

### Expected behavior

Proper loading and functioning of interface when using a prefix.

### Environment

- Docker Image : argilla/argilla-server:latest
