### ISSUE TITLE
[BUG-python/deployment] mounted volume permissions

### ISSUE THREAD

**Issue by aleksvercau** [argilla-io/argilla#5793]
### Describe the bug

I deployed Argilla in my Azure k8s cluster and got a permissions error for the mounted volume under `/data` in the worker pod. Not sure whether this issue only occurs in Azure or in all k8s clusters.

### Stacktrace and code to create the bug

Use the k8s deployment available in the Argilla repo.

### Expected behavior

No permission issues for the `/data` folder in the worker.

### Environment

- Argilla Version [e.g. 1.0.0]:
- ElasticSearch Version [e.g. 7.10.2]:
- Docker Image (optional) [e.g. argilla:v1.0.0]:

### Additional context

This can easily be fixed by adding an initContainer in the worker deployment:

 ```
   spec:
      initContainers:
        - name: volume-permissions
          image: busybox
          command: [ "sh", "-c", "chown -R 1000:1000 {{ .Values.argilla.persistence.mountPath }}" ]
          volumeMounts:
          - name: argilla-data
            mountPath: {{ .Values.argilla.persistence.mountPath | quote }}
```
