### ISSUE TITLE
[BUG-python/deployment] Upgrading to Argilla v2 does not populate the metadata of migrated datasets, breaking `to_hub()` for same metadata key as a field

### ISSUE THREAD

**Issue by mpjuhasz** [argilla-io/argilla#5821]
### Describe the bug

We are migrating from argilla v1.29.0 to v2.0.0. We've had all of our datasets in the `FeedbackDataset` format, which based on the [migration guide](https://docs.argilla.io/v2.0/how_to_guides/migrate_from_legacy_datasets/) is compatible with the new v2 `Dataset`, and transforms with no issues. 

This is true for the records, which get correctly transformed into the v2 format, without any issues. However, the `settings` attribute of these newly migrated datasets are not correctly populated. These were previously set in the top-level fields such as `questions`, `fields`, `metadata` etc. setting the schema for the dataset. As I understand, all of this information is now tracked under `Settings`. The `fields` and `questions` are populated correctly, however none of the metadata fields appear.

Because all of our datasets had the same schema, I've tried the following: backfilling the new v2 Datasets objects with the correct settings. This fails however, because the `settings` cannot be updated on a dataset that has already been published. 

This issue was problematic for us, because we wanted to back up these datasets into Huggingface, using the `Dataset.to_hub()` method. This, however relies on flattening the dataset based on the `Settings`. 

A workaround I tried was to pull the dataset, locally overwrite the settings by adding the metadata fields manually (this is allowed) and then push to the hub. At this point, however I've come up against an implicit assumption for the fields: no two fields in the flattened dataset can have the same key. As it happens our datasets have a `field` of the name `text`, as well as a metadata field of the same name, which starts causing issues when pushing to the hub. The metadata fields I couldn't overwrite, offering no more potential workarounds.

### Stacktrace and code to create the bug

Our docker compose after the upgrade:

```yaml
services:
  argilla:
    image: argilla/argilla-server:v2.0.0
    container_name: argilla_server
    restart: unless-stopped
    ports:
      - 6900:6900
    environment:
      ARGILLA_HOME_PATH: /var/lib/argilla
      ARGILLA_ELASTICSEARCH: http://elasticsearch:9200
      ARGILLA_AUTH_SECRET_KEY: ${ARGILLA_AUTH_SECRET_KEY:? Please generate a 32 character random string with `openssl rand -hex 32`}
      ARGILLA_ENABLE_TELEMETRY: 0
      DEFAULT_USER_ENABLED: false
    volumes:
    - argilladata:/var/lib/argilla
    networks:
      - argilla

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    environment:
      - node.name=elasticsearch
      - cluster.name=es-argilla-local
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - argilla
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticdata:/usr/share/elasticsearch/data/
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
      - argilla
networks:
  argilla:
    driver: bridge
volumes:
  elasticdata:
  argilladata:
```

## Settings after migration:
```
dataset = client.datasets(name=dataset_name, workspace=workspace)
print(dataset.settings)

> Settings(guidelines=Highlight the entity if it is present in the text, allow_extra_metadata=True, distribution=OverlapTaskDistribution(min_submitted=1), 
fields=[TextField(name=text, title=Text, description=None, type=text, required=True) 
], questions=[SpanQuestion(name=entities, title=Entities, description=None, type=span, required=True) 
], vectors=[], metadata=[])
```

## Push to hub:
```
dataset = client.datasets(name=dataset_name, workspace=workspace)
dataset.to_hub(hub_repo, token=os.getenv("HF_TOKEN"))


> .venv/lib/python3.10/site-packages/argilla/records/_io/_ │
│ generic.py:106 in _record_to_dict                                                                │
│                                                                                                  │
│   103 │   │                                                                                      │
│   104 │   │   record_dict = record.to_dict()                                                     │
│   105 │   │   if flatten:                                                                        │
│ ❱ 106 │   │   │   record_dict.update(                                                            │
│   107 │   │   │   │   **record_dict.pop("fields", {}),                                           │
│   108 │   │   │   │   **record_dict.pop("metadata", {}),                                         │
│   109 │   │   │   │   **record_dict.pop("vectors", {}),                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: dict.update() got multiple values for keyword argument 'text'
```

### Expected behavior

- the `settings` attribute gets populated from the dataset's old schema as part of the migration
- if not that, then: `settings` can be updated for datasets that have been already published (or at least in cases when settings are empty!)
- implicit assumptions about clashing keys made explicit and / or handled as part of data-upload / migration: I now have a bunch of datasets that are corrupted, because I can't run basic methods on them that involve flattening. I should be avoided: either raising errors when clashing keys, or by renaming them at creation time

### Environment

- Argilla Version [e.g. 1.0.0]: 2.7.0
- ElasticSearch Version [e.g. 7.10.2]: 8.5.3
- Docker Image (optional) [e.g. argilla:v1.0.0]: v2.0.0
